export const sidebarImgs = [
    {
        company: "kholer",
        url: "https://www.toptal.com/designers/subtlepatterns/uploads/light-grey-terrazzo.png",
    },
];

// Kohler's products
export const allProds = [
    "Kitchen Faucet",
    "Kitchen Sink, Toilet, Bidet",
    "Bathroom, Kitchen Sets",
    "Sink",
    "General",
    "Toilet",
    "Bathroom Faucet",
    "Faucet",
    "Bathroom Item",
    "Bathtub",
    "Bathroom",
    "Bathroom Tub",
    "Generator",
    "Shower",
    "Engines",
    "Kitchen Sink",
    "Bathroom sink",
    "bathtub",
    "Sink faucet, Toilet",
    "Hydro Jetting",
    "BathTub",
];

export const mccainProducts = [
    "Frozen Pizza",
    "Cheese and Bacon Pizza Pockets",
    "Frozen Chippies",
    "Herb & Parmesan SCHNITZEL with Farm Picked Vegetables",
    "Anzsc biscuit",
    "Pizza dough balls",
    "Pizza Pocket",
    "Pizza",
    "Frozen Pizza",
    "MCCAIN DEEP 'N DELICIOUS CHOCOLATE",
    "MCCAIN TASTI TATERS",
    "MCCAIN ONION RINGS",
    "MCCAIN DEEP 'N DELICIOUS VANILLA CAKE",
    "MCCAIN HASHBROWNS",
    "MCCAIN SWEET POTATO PLANK CUT FRIES",
    "MCCAIN SPICY WEDGES",
    "French fries",
    "Mcains Lasagne",
    "Chips",
    "Potato Products",
    "Working's",
    "McCain Ash Browns",
    "McCain Foods",
    "Customer Service",
    "Pizza",
    "McCain's food",
    "Roasted garlic wedges",
    "Onion Chips",
    "Roast tatties",
    "McCain stir fry",
    "lamb cutlet meal",
    "Vegetables",
    "Onions",
    "Chilli Cheese Fries",
    "Frozen Products",
    "Beans",
    "Frozen Beans",
    "Fries",
    "Stri Fry Veggies",
    "McCain Dishruption challenge",
    "McCain Group"
];

export const pjiProducts = [
    "AI Supreme Delight",
    "Pixel Perfect Pepperoni",
    "Cyborg BBQ Chicken",
    "Binary Basil Pesto",
    "Neural Network Neapolitan",
    "Algorithmic Alfredo",
    "Quantum Quattro Formaggi",
    "Virtual Veggie Extravaganza",
    "Machine Learning Margherita",
    "Robotic Ranch Revolution",
]
